### ISSUE TITLE
Different Output with other library

### ISSUE THREAD

**Issue by kisenaa** [samuel-lucas6/Geralt#12]
I was using geralt because it uses libsodium implementation but it seems it produce different output with other library such as Isopoh.Cryptography.Argon2 . 
```
       public IActionResult Test(string password)
       {
           byte[] passwordBytes = Encoding.UTF8.GetBytes(password);
           // salting is hex string
           string salting = "6c6f62616c6f62613264616477696639"; // plain text : lobaloba2dadwif9
           byte[] salt = Convert.FromHexString(salting);

           var config = new Argon2Config
           {
               Type = Argon2Type.HybridAddressing, //argon2id
               Version = Argon2Version.Nineteen,
               TimeCost = 2, // iterations
               MemoryCost = 8192, // memory
               Lanes = 1,  // paralism
               Threads = Environment.ProcessorCount,
               Password = passwordBytes,
               Salt = salt, 
           };
           using var argon2client = new Argon2(config);
           using var hash = argon2client.Hash();
           string hashstring = config.EncodeString(hash.Buffer);

           Span<byte> okm = new byte[32];
           Argon2id.DeriveKey(okm, passwordBytes, salt, 2, 8192);

            string geraltString = Convert.ToHexString(okm);
            string IsopohCryptographString = Convert.ToHexString(hash.Buffer);

           return Ok(new{ IsopohCryptographString, geraltString });
       }
  ```
  
  If i call the function with password = "string" , the output is :
  isopohCryptographString: "E6274D67634B68F62F8764F7DD011E34F9B208003B153AAD69E03185BAB963C3"  (correct)
  geraltString: "295C6D6889530B62F28980FA79208C869E0835D4F3D632F008D08C5447169E63"  (false)
  
  whats wrong with my code ?

**Comment by samuel-lucas6** [comment]
Thanks for the code snippet and inputs/outputs. Isopoh.Cryptography.Argon2 interprets `MemoryCost` as the number of 1024-byte blocks, whereas Geralt does `memorySize` in bytes. Thus, `memorySize = 8192` with Geralt is equivalent to `MemoryCost = 8` in Isopoh. The strings then match.

However, if you can, I recommend using the [Argon2id.ComputeHash()](https://www.geralt.xyz/password-hashing#computehash) function for a string output.

**Comment by kisenaa** [comment]
Thank you . So Argon2id.computehash function is to encode the hash to argon2 output format ?
like $ argon2id $....

**Comment by samuel-lucas6** [comment]
> Thank you . So Argon2id.computehash function is to encode the hash to argon2 output format ?
> like $ argon2id $....

Correct, and [Argon2id.VerifyHash()](https://www.geralt.xyz/password-hashing#verifyhash) will verify such a string.
