### ISSUE TITLE
Clarify documentation on IncrementalXChaCha20Poly1305

### ISSUE THREAD

**Issue by Jack-Edwards** [samuel-lucas6/Geralt#6]
> For encryption, the header is filled with a random nonce. _It MUST be prepended to the first ciphertext chunk._

It's my understanding the header should remain detached from the ciphertext.  This is how the unit tests behave.

**Comment by samuel-lucas6** [comment]
Thanks for highlighting this poor wording. You're correct; I've changed it to the following:

> For encryption, the header is filled with a random nonce. It MUST be sent/stored before the sequence of ciphertext messages because it is required to decrypt the stream.

That follows [libsodium's](https://doc.libsodium.org/secret-key_cryptography/secretstream) phrasing. Feel free to reopen this if you think anything else can be improved :)
